# These are supported funding model platforms

github: # izzianityforlife 2298741867 izzianity27 LLC izzianity27 izzianity
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # npm/babel
community_bridge: # izzianity27 LLC izzianity27 izzianity izzianityforlife cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
lfx_crowdfunding: # izzianity izzianity27 izzianityforlife izzianity27 LLC  cloud-foundry
polar: # Replace with a single Polar username
buy_me_a_coffee: # izzianity27 izzianity izzianityforlife 2298741867
thanks_dev: # thanks.dev izzianity27@outlook.com
custom: #  ['microsoft', 'google' 'grok' 'chat gbt']
